language: swift
osx_image: xcode8.3.3
script:
    - xcodebuild clean test -project Analytics.xcodeproj -scheme Analytics -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet